### PR TITLE
Major UI update

### PR DESCRIPTION
**Pull request by Cwjiee**
Changes
- update login page UI
- update index page UI

### CODE REVIEW

**Comment by Tharshen2124** [comment]
Screenshot 2024-05-25 165039
Finished up the `/add-restaurant` page.

**Comment by Cwjiee** [comment]
image

**Comment by Tharshen2124** [comment]
Screenshot 2024-05-26 011453

Redesign for the /randomise page

**Comment by Tharshen2124** [comment]
the container having all the lists is scrollable btw

**Comment by Cwjiee** [comment]
LGTM

**Comment by Tharshen2124** [comment]
LGTM as well. Can we merge it? @Cwjiee

**Pull request merged**
